[project]
id = "machete"
version = "0.1.0"
mach = "^5.3"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.windows-x86_64]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.linux-aarch64]
isa = "aarch64"
os  = "linux"
abi = "aapcs64"

[artifact.machete]
kind = "bin"
entry = "root.mach"
out = "bin/machete{artifact.suffix}"
targets = ["*"]
link = ["kernel32"]
need = []

[link.kernel32]
source = "system"
name = "kernel32.dll"
os = ["windows"]
isa = ["*"]
abi = ["*"]
export = false

[profile.debug]
default = true
opt = 0
debug = true
simd = "scalarize"
vectorize = false
float_reassoc = false

[profile.release]
opt = 2
debug = false
simd = "scalarize"
vectorize = true
float_reassoc = false

[dep.std]
git = "https://github.com/briar-systems/mach-std"
ref = "tag/v3.2.0"
