"""Generate src/replines.mach from repertoire.txt: the repertoire's
lines as coordinate moves, grouped into systems (the Vienna, the Marshall
...), which src/repertoire.mach plays out at start-up.

    python harness/repgen.py [--txt repertoire.txt] [--out src/replines.mach]

Every move is checked here with python-chess, so a typing mistake in the
repertoire is caught with its line number instead of becoming a line the
engine silently stops following. Prints how many positions each side gets.
"""
import argparse
import re
import sys

import chess


def read_lines(path):
    lines = []
    for number, raw in enumerate(open(path, encoding="utf-8"), 1):
        text = raw.split("#")[0].strip()
        if not text:
            continue
        head, _, moves = text.partition(":")
        side, _, system = head.partition(" ")
        if side not in ("white", "black") or not system.strip() or not moves.strip():
            raise SystemExit("{}:{}: a line is 'white <system>: <moves>' or 'black <system>: <moves>'".format(path, number))
        board = chess.Board()
        spelled = []
        for token in moves.split():
            token = re.sub(r"^\d+\.(\.\.)?", "", token)
            if not token:
                continue
            try:
                move = board.parse_san(token)
            except ValueError:
                raise SystemExit("{}:{}: {} is not legal after {}".format(
                    path, number, token, " ".join(spelled) or "the start"))
            spelled.append(move.uci())
            board.push(move)
        lines.append((side, system.strip(), spelled))
    return lines


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--txt", default="repertoire.txt")
    parser.add_argument("--out", default="src/replines.mach")
    args = parser.parse_args()

    lines = read_lines(args.txt)
    systems = []
    for side, system, _ in lines:
        if (side, system) not in systems:
            systems.append((side, system))
    if len(systems) > 10:
        raise SystemExit("at most 10 systems: each is one digit in replines.mach")
    owned = {"white": set(), "black": set()}
    for side, _, moves in lines:
        board = chess.Board()
        for uci in moves:
            mover = "white" if board.turn == chess.WHITE else "black"
            board.push_uci(uci)
            if mover == side:
                owned[side].add(board._transposition_key())
    text = ";".join("{} {}".format(systems.index((side, system)), " ".join(moves)) for side, system, moves in lines)
    longest = max(len(moves) for _, _, moves in lines)
    out = [
        "# GENERATED by harness/repgen.py from repertoire.txt; edit that file, not this one.",
        "#",
        "# The repertoire's lines as coordinate moves, each led by the digit of its",
        "# system, lines separated by ';'. SYSTEM_SIDE has a 'w' or 'b' per system",
        "# for the side whose moves it prefers. src/repertoire.mach plays the lines",
        "# out once and keeps the positions they reach.",
        "",
        "use std.types.string.str;",
        "",
        "# {}".format(", ".join("{} {} {}".format(k, side, name) for k, (side, name) in enumerate(systems))),
        "pub val SYSTEMS:     i64 = {};".format(len(systems)),
        "pub val SYSTEM_SIDE: str = \"{}\";".format("".join(side[0] for side, _ in systems)),
        "pub val LINES:       str = \"{}\";".format(text),
        "pub val POSITIONS:   i64 = {};".format(len(owned["white"]) + len(owned["black"])),
        "pub val LONGEST:     i64 = {};".format(longest),
        "",
    ]
    with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out))
    print("{} lines in {} systems, {} positions for White and {} for Black, longest {} plies -> {}".format(
        len(lines), len(systems), len(owned["white"]), len(owned["black"]), longest, args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
